live_config_reload: true

env:
  TERM: xterm-256color

window:
  decorations: buttonless
  opacity: 0.9
  dynamic_padding: false
  padding:
    x: 25
    y: 20

font:
  normal:
    family: "SFMono Nerd Font"
    style: Medium
  italic:
    family: "SFMono Nerd Font"
    style: Medium Italic
  bold:
    family: "SFMono Nerd Font"
    style: Heavy
  bold_italic:
    family: "SFMono Nerd Font"
    style: Heavy Italic
  size: 14.0

  key_bindings:
    - { key: T, mods: Command, chars: "\x02\x63" }

import:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
